### ISSUE TITLE
(Mono) Parenthetical spacing/centering

### ISSUE THREAD

**Issue by jfaz1** [quiple/galmuri#47]
Hello,

I love using this font for programming, only thing that makes it a little bit annoying for code is that the parentheses seem to not be centered, making it confusing when the cursor overlaps:
![image](https://github.com/quiple/galmuri/assets/56184947/397eb5d7-c72d-447f-94a8-4be85039bb12)
![image](https://github.com/quiple/galmuri/assets/56184947/1d2fa2ad-a052-4396-99d7-9cee2ab62840)

I'm wondering if it's possible to space them out a tiny bit more to make the separation more obvious. I'm using `GalmuriMono` so obviously the same character width needs to be retained, but I think you can manage this by shifting the closing parenthesis `)` a bit to the right, and *maybe* the opening parenthesis `(` a bit to the left. 

The closing parenthesis is the more problematic one, almost looks like it's going outside of the cursor:
![image](https://github.com/quiple/galmuri/assets/56184947/ec3913f2-e5d7-45bc-9277-f9885ca142ed)
Compared to the opening parenthesis, which appears more centered:
![image](https://github.com/quiple/galmuri/assets/56184947/45469d37-a3d5-4be2-9b19-e3c44f4b428a)

Thanks!

**Comment by quiple** [comment]
I Moved the parentheses 1px left and right so that they are centered. However, that the rightmost 1px is the margin between the glyphs, so the glyphs may appear to be slightly off to the left.
