### ISSUE TITLE
Bitmap ttf seems to be damaged

### ISSUE THREAD

**Issue by TakWolf** [quiple/galmuri#54]
Windows Preview:

<img width="794" alt="E7F87BBFAB3E15428D899A1F75B3E9FA" src="https://github.com/quiple/galmuri/assets/6064962/76bc64ac-ae5f-478b-9484-a86f37133d80">

FontForge:

![39BB6C5CC6136CE33585F72A65454334](https://github.com/quiple/galmuri/assets/6064962/1345c1d9-d215-4f5f-b911-4303ed98deec)

It has an incorrect file size.

<img width="186" alt="image" src="https://github.com/quiple/galmuri/assets/6064962/be25e867-2c12-416f-9367-f532810a78c1">

I have parsed the font and it has an 'ebdt' table, but the data is incorrect

**Comment by quiple** [comment]
Bitmap TTFs contain only 16px bitmap strikes data, not outline data.

In Windows Font Preview, bitmap data at 16px should display at 12pt size, but depending on the user's UI scaling setting, it may not.

And in FontForge, when you first open a font file, you can see the font data by choosing to load the bitmap font at 16px size and selecting "16 pixel bitmap" from the "View" menu.

<img width="1316" alt="스크린샷 2024-04-28 11 53 08" src="https://github.com/quiple/galmuri/assets/11014257/ceb50377-3568-418a-b333-ef0b42210af3">

Thank you!

**Comment by TakWolf** [comment]
I got it, such is the case.
