### ISSUE TITLE
숫자 고정폭이 기본적용된 폰트도 만들어주실 수 있을까요?

### ISSUE THREAD

**Issue by ueyhuom** [quiple/galmuri#55]
파일 탐색기용으로 쓰는 Total Commander나 Double Commander, 또는 엑셀에서 Galmuri11 폰트를 사용하는데요.

이럴때 문제는 숫자가 고정폭이 아니어서 엑셀 같이 윗 셀과 아랫 셀의 숫자 자리수를 보고 비교해야 할때 숫자들의 가로폭이 달라서 쉽게 비교가 불가해서 어쩔수 없이 다른 폰트를 쓰고 있습니다. 그러고 보니까 굴림 폰트는 (고정폭 폰트인 '굴림체'가 아니어도) 숫자들은 고정폭이라서 문제가 없었습니다.

https://galmuri.quiple.dev/ 에서 보면 [사용할 수 있는 OpenType 기능] 이라고 하면서 [고정폭 숫자 (tnum)] 가 있던데, 이 기능을 어떻게 쓰는건지 잘 모르겠지만 아마 폰트에 대한 기능을 다양하게 설정할 수 있는 웹페이지? 같은데서 쓸수있는 기능이지요?

일반적인 프로그램에서는 폰트의 종류와 글씨 크기만 설정 가능하므로, 숫자고정폭 기능은 따로 설정이 불가능한것 같습니다.

대안으로 Galmuri Mono 11 폰트를 써봤는데 이러면 너무 가로폭이 좁아서 가독성이 좀 좋지 않았습니다. (특히 영문자)

그래서 혹시 가능하시다면 (폰트 기능이 설정불가한 프로그램에서도 고정폭 숫자를 쓸 수 있도록) 기본적으로 고정폭 숫자가 적용되어있는 폰트를 만들어주시면 정말 감사하겠습니다.

**Comment by quiple** [comment]
안녕하세요, 아쉽지만 기본적으로 고정폭 숫자가 적용되어 있는 폰트는 제공하고 있지 않습니다.

대신 [OpenType Feature Freezer](https://twardoch.github.io/fonttools-opentype-feature-freezer/) 또는 [FontFreeze](https://mutsuntsai.github.io/fontfreeze/) 같은 도구를 사용해서 고정폭 숫자 기능을 고정시켜 사용하시는 것을 추천드립니다.
