### ISSUE TITLE
혹시 ms 오피스나 아래아한글에서 갈무리체로 한글을 다른 글꼴처럼 입력할 수 있게 하려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by GumballTY** [quiple/galmuri#7]
동영상 보기: [https://drive.google.com/file/d/1lwHJSnVR7-FI7crF0-lV_mM29PQ6jQaB/view?usp=sharing](url)

제가 갈무리체를 설치하고 ms 오피스에서 사용하려고 하니까 한글을 입력할 때 기본글꼴로 바뀌었습니다. 그래서 제가 아무리 알아보고 시도해봤지만 결국 이 문제를 고칠 수 없었습니다. 영상에서 보시는 것처럼 입력을 한 뒤에 글꼴을 바꾸면 한글도 갈무리체로 바뀌는데 또 다른 한글을 입력하면 또 기본글꼴로 바뀌게 됩니다. 게다가 아래아한글에서는 한글뿐만 아니라 영어까지 입력 뒤에 글꼴을 바꿔도 갈무리체가 아니라 기본글꼴로만 표기되고요. 제가 제어판의 글꼴에 들어가보니까 일본어 글꼴로 되어있어서 그런 것 같은데 이걸 한글 글꼴로 바꿀 순 없나요?

**Comment by quiple** [comment]
말씀하신 대로 일본어로 설정되어 있어서 생기는 문제 같네요.

현재 Bits'N'Picas만 사용해서 TTF를 생성하는데 Bits'N'Picas에 그런 부분을 설정하는 기능이 없다 보니 이렇게 된 모양입니다. 만들어진 TTF를 FontForge 같은 도구로 메타데이터를 수정해주면 될 것 같은데, 가능할지 한번 알아보겠습니다..

**Comment by GumballTY** [comment]
네. 감사합니다. 최대한 빨리 해결되었으면 좋겠네요.

2022년 6월 25일 (토) 오전 2:44, Minseo Lee ***@***.***>님이 작성:

**Comment by GumballTY** [comment]
제가  Fontlab으로 알아보니까 글꼴이 지원하는 코드페이지가 일본어로밖에 안 되어 있어서 그런 것 같네요. 이 코드 페이지를
한글완성형(Korean Wansung) 하고 한글조합형(Korean Johab)으로 바꾸면 될 것 같습니다. 이왕이면 갈무리체에 있는
모든 언어를 지원하면 더 좋을 것 같습니다.

2022년 6월 25일 (토) 오전 6:09, Butters Lee ***@***.***>님이 작성:

**Comment by GumballTY** [comment]
참고로 저는 이걸 Fontlab 체험판으로 알아냈는데 제가 직접 수정해서 저장하려니까 체험판이라 그런지 오류만 뱉고 저장이 안
되더라고요...

2022년 6월 25일 (토) 오전 11:41, Butters Lee ***@***.***>님이 작성:

**Comment by quiple** [comment]
FontForge로 확인해 봤을 때도 Galmuri7, 9, 11 Bold는 OS/2 코드페이지 설정이 안 되어 있는데 이유는 모르겠지만 Galmuri11만 코드페이지가 JIS로 되어 있는 걸 확인했습니다.

다만 이게 GUI 환경에서는 수정할 수 있는데 스크립트 환경에서 지원하지를 않는 모양이라서 다른 툴도 좀 알아보는 중입니다..

당장 필요하시면 FontForge를 설치하셔서 파일을 열고 `Element` -> `Font Info…` -> `OS/2` -> `Charsets` -> `MS Code Pages`에서 `949 Korean Wansung`을 선택하시고 저장하신 후에 `File` -> `Generate Fonts…` 누르시고 `TrueType` 선택하시고 창 뜨는 거 대충 무시하시고 파일 생성하시면 됩니다.

**Comment by quiple** [comment]
[g11.zip](https://github.com/quiple/galmuri/files/8986940/g11.zip)
수정한 파일도 올려 드립니다.

**Comment by quiple** [comment]
해결되었습니다. [최신 릴리스](https://github.com/quiple/galmuri/releases/latest)를 확인해주세요.

[AFDKO](https://github.com/adobe-type-tools/afdko)가 Ubuntu에서 발생하는 문제가 드디어 픽스되어서 바로 해결하였습니다.

**Comment by GumballTY** [comment]
네. 감사합니다. 이제 ms 워드하고 아래아한글에서도 잘 되는군요...
정말로 감사합니다.
[image: 인증샷.png]

2022년 6월 27일 (월) 오전 12:30, Minseo Lee ***@***.***>님이 작성:
